name: Build iOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up Xcode
        uses: actions/setup-xcode@v2
        with:
          xcode-version: '13.0'  # Atualize para a versão do Xcode que você está usando

      - name: Build iOS App
        run: |
          xcodebuild clean build \
            -workspace YourWorkspace.xcworkspace \  # Substitua pelo caminho correto para o seu workspace
            -scheme YourScheme \  # Substitua pelo nome correto do seu esquema
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 13'
